version: '3'

networks:
  blog_network:
    driver: bridge

services:

  #nginx
  nginx-serivice:
    image:  nginx:stable-alpine
    container_name: nginx-container
    ports:
      - "8080:80"
    volumes:
      - ./app:/var/www/project
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php82-service
      - mysql8-service
    networks:
      - blog_network

  #php
  php82-service:
    build:
      context: .
      dockerfile: ./php/Dockerfile
    container_name: php82-container
    ports:
      - "9000:9000"
    volumes:
      - ./app:/var/www/project
    networks:
      - blog_network

  #mysql
  mysql8-service:
    image: mysql:8
    container_name: mysql8-container
    ports:
      - "3306:3306"
    volumes:
      - ./mysql:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_PASSWORD: secret
    networks:
      - blog_network


  #node
  node-service:
    image: node:latest
    container_name: node-container
    volumes:
      - ./app:/var/www/project
    working_dir: /var/www/project
    networks:
      - blog_network

  # elasticsearch ——————————————————————————————————————————————————————————————

  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:6.8.3
    ports:
      - "9209:9200"
    environment:
      - "discovery.type=single-node"
      - "bootstrap.memory_lock=true"
      - "ES_JAVA_OPTS=-Xms1G -Xmx1G"
      - "xpack.security.enabled=false"
      - "http.cors.enabled=true"
      - "http.cors.allow-origin=*"
    networks:
      - blog_network

  elasticsearch-head:
    container_name: elasticsearch-head
    depends_on:
      - elasticsearch
    image: tobias74/elasticsearch-head:6
    ports:
      - "9109:9100"
    networks:
      - blog_network